import { supabase } from "@/lib/supabase";
import StoriesGallery from "@/components/StoriesGallery";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ParticleBackground from "@/components/ParticleBackground";
import ScrollProgressBar from "@/components/ScrollProgressBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Story Gallery — Viral Scripts Created by StoryFlip Users",
  description:
    "Browse viral short-form scripts generated by the StoryFlip community. Cheating, horror, true crime, AITA, and more — real scripts ready to inspire your next video.",
};

export const revalidate = 60;

export default async function StoriesPage() {
  const { data: scripts } = await supabase
    .from("scripts")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(60);

  return (
    <main
      style={{
        minHeight: "100vh",
        backgroundColor: "#09090b",
        color: "white",
        overflowX: "hidden",
      }}
    >
      <ParticleBackground />
      <ScrollProgressBar />
      <Navbar />
      <StoriesGallery scripts={scripts || []} />
      <Footer />
    </main>
  );
}